In [2]:
import logging
import os
import time
import uuid
from abc import ABC, abstractmethod

import accelerate
import imageio
import numpy as np
import pytorch_fid
import pytorch_fid.fid_score
import torch
import wandb
from accelerate import Accelerator
from torch import Tensor, optim
import sys, os
sys.path.append(".")
sys.path.append("..")
os.chdir("/home/jikewct/public/jikewct/Repos/ml_code")
from lib import tensor_trans

/home/jikewct/anaconda3/envs/py3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
y = torch.randn(4,2,1)
trans_y = tensor_trans.mask_sample_in_batch_by_cond(y, 0.5)
print(y, trans_y)

In [ ]:
y = torch.randn(4,2,1)
x = torch.randn(1,2,1)

trans_y = tensor_trans.replace_sample_by_cond(y,x,0.9)
print(y)
print(x)
print(trans_y)

In [4]:
trans_y[0]

tensor([[-0.3147],
        [-2.4404]])

In [ ]:
beta_max = 0.0120
beta_min = 0.00085
N = 1000
def get_schedule(beta_max, beta_min, N):
    betas = np.linspace(beta_min, beta_max,N)
    alphas = 1 - betas
    alphas_cum = np.cumprod(alphas)
    return alphas_cum

a1 = get_schedule(beta_max, beta_min, 1000)
a2 = get_schedule(beta_max, beta_min, 10000)

print(a1[:10])
print(a2[:100])


In [7]:
a = torch.randn((2,3))
b = torch.where(a > 0, a, 1e-4)
print(a)
print(b)

tensor([[-1.0605,  0.3062,  0.5727],
        [-1.8373, -0.4808,  0.2450]])
[[9.9999997e-05 3.0620062e-01 5.7266849e-01]
 [9.9999997e-05 9.9999997e-05 2.4496992e-01]]
